USE [master]
GO

/****** Object:  Database [stockmann]    Script Date: 07/02/2013 19:20:21 ******/
DROP DATABASE [stockmann]

CREATE DATABASE [stockmann] ON  PRIMARY 
( NAME = N'stockmann', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL10.MSSQLSERVER\MSSQL\DATA\stockmann.mdf' , SIZE = 3072KB , MAXSIZE = UNLIMITED, FILEGROWTH = 1024KB )
 LOG ON 
( NAME = N'stockmann_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL10.MSSQLSERVER\MSSQL\DATA\stockmann_log.ldf' , SIZE = 1024KB , MAXSIZE = 2048GB , FILEGROWTH = 10%)
GO

ALTER DATABASE [stockmann] SET COMPATIBILITY_LEVEL = 100
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [stockmann].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [stockmann] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [stockmann] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [stockmann] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [stockmann] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [stockmann] SET ARITHABORT OFF 
GO

ALTER DATABASE [stockmann] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [stockmann] SET AUTO_CREATE_STATISTICS ON 
GO

ALTER DATABASE [stockmann] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [stockmann] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [stockmann] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [stockmann] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [stockmann] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [stockmann] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [stockmann] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [stockmann] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [stockmann] SET  DISABLE_BROKER 
GO

ALTER DATABASE [stockmann] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [stockmann] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [stockmann] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [stockmann] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [stockmann] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [stockmann] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [stockmann] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [stockmann] SET  READ_WRITE 
GO

ALTER DATABASE [stockmann] SET RECOVERY FULL 
GO

ALTER DATABASE [stockmann] SET  MULTI_USER 
GO

ALTER DATABASE [stockmann] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [stockmann] SET DB_CHAINING OFF 
GO


